apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
 name: wapi-ingress
 namespace: wapi
 annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  rules:
   - host : weatherapp #your DNS 
     http:
       paths:
         - path: /wapi
           pathType: Prefix
           backend:
             service:
               name: wapi-service
               port:
                 number: 80