apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp-deployment
  namespace: {{ .Values.namespace }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: webapp
  template:
    metadata:
      labels:
        app: webapp
        environment: {{ .Values.env }}
    spec:
      containers:
        - name: webapp-container
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          ports:
            - containerPort: 3000 
