apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
 name: mapi-ingress
 namespace: mapi
 annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  rules:
   - host : weatherapp #your DNS 
     http:
       paths:
          - path: /mapi
            pathType: Prefix
            backend:
              service:
                name: mapi-service
                port:
                  number: 80